Repository INFLUY/Influy-FE, pull requests merged in 2025-05, with the labels that each got.

#4 [DESIGN] global.css 수정
  src/styles/global.css
Labels: design

#6 [FEAT] 유저뷰 상품 컴포넌트
  .prettierrc
  package-lock.json
  package.json
  public/img1.png
  src/assets/icon/common/CheckBox16Off.svg
  src/assets/icon/common/CheckBox16On.svg
  src/assets/icon/common/LayoutButton.svg
  src/assets/icon/user/Heart.svg
  src/assets/icon/user/HeartActive.svg
  src/components/index.ts
  src/components/layout/GlobalLayout.tsx
  src/components/user/Chip.tsx
  src/components/user/Product.tsx
  src/components/user/ScrapButton.tsx
  src/pages/index.ts
  src/pages/user/SellerProfile.tsx
  src/routes/AppRouter.tsx
  src/routes/path.ts
  src/styles/global.css
  src/types/types.ts
Labels: feature, chore, design

#7 [FEAT] 유저뷰 상품페이지
  src/assets/icon/common/ArrowIcon.svg
  src/assets/icon/common/Chevron.svg
  src/assets/icon/common/EditIcon.svg
  src/assets/icon/common/LayoutAlbumButton.svg
  src/assets/icon/common/LayoutListButton.svg
  src/assets/icon/common/LinkIcon.svg
  src/assets/icon/common/MinusIcon.svg
  src/assets/icon/common/PlaceHolderIcon.svg
  src/assets/icon/common/SearchIcon.svg
  src/assets/icon/common/ShareIcon.svg
  src/components/common/ExternalLinkChip.tsx
  src/components/common/NoticeBanner.tsx
  src/components/common/SellerProfileCard.tsx
  src/components/common/Tab.tsx
  src/components/index.ts
  src/components/seller/Item.tsx
  src/components/user/Chip.tsx
  src/components/user/Item.tsx
  src/components/user/SellerProfileHeader.tsx
  src/pages/index.ts
  src/pages/seller/SellerMyPage.tsx
  src/pages/user/sellerProfile/ReviewTab.tsx
  src/pages/user/sellerProfile/SelectionTab.tsx
  src/pages/user/sellerProfile/SellerProfile.tsx
  src/routes/AppRouter.tsx
  src/routes/path.ts
  src/styles/global.css
  src/types/types.ts
  src/utils/formatNumber.ts
Labels: feature, chore, design

#10 [FEAT] BottomSheet 컴포넌트 구현
  index.html
  src/components/common/BottomSheet.tsx
  src/hooks/useBottomSheetGesture.ts
  src/pages/user/sellerProfile/SellerProfile.tsx
  src/styles/global.css
Labels: feature

#12 [FEAT] 셀러 공통 컴포넌트 제작 (#5)
  src/assets/icon/common/Warning.svg
  src/components/index.ts
  src/components/seller/common/Button.tsx
  src/components/seller/common/Button.types.ts
  src/components/seller/common/CategoryChip.tsx
  src/components/seller/common/DetailInput.tsx
  src/components/seller/common/TipTooltip.tsx
  src/components/seller/item/registration/CategoryMultiSelector.tsx
  src/constants/productCategories.ts
  src/hooks/useAutoResizeTextArea.ts
  src/pages/index.ts
  src/pages/seller/item/ItemRegistrationPage.tsx
  src/routes/AppRouter.tsx
  src/routes/path.ts
  src/styles/global.css
  src/utils/validation.ts
Labels: feature, design
