Repository INFLUY/Influy-FE, pull requests merged in 2025-08, with the labels that each got.

#75 [Bug] 홈 및 presigned url 등 버그 수정
  src/api/presignedUrl/putPresignedUrl.ts
  src/components/common/SellerProfileCard.tsx
  src/components/common/VanillaProfileImageUploader.tsx
  src/components/common/card/HorizontalRankingCard.tsx
  src/components/common/card/ItemAlbumCard.tsx
  src/components/seller/home/MyProductStatus.tsx
  src/components/seller/item/administration/EditStatusChip.tsx
  src/components/seller/item/administration/SellerMyItemCard.tsx
  src/components/seller/item/registration/ItemForm.tsx
  src/components/seller/item/registration/PeriodDropdown.tsx
  src/components/seller/my/SellerMyProfileHeader.tsx
  src/components/user/common/Chip.tsx
  src/components/user/common/ItemGridCard.tsx
  src/components/user/home/HomeCommonSection.tsx
  src/components/user/seller/SellerProfileHeader.tsx
  src/pages/auth/WelcomePage.tsx
  src/pages/seller/item/ItemRegistrationPage.tsx
  src/pages/seller/sellerMyPage/MySelectionTab.tsx
  src/pages/user/home/CategoryPage.tsx
  src/pages/user/market/SellerProfile.tsx
  src/routes/AppRouter.tsx
  src/routes/path.ts
  src/schemas/itemSchema.ts
  src/services/home/query/useGetCloseDeadlineItem.ts
  src/services/home/query/useGetHomeQuestions.ts
  src/services/home/query/useGetPopularItem.ts
  src/services/home/query/useGetRecommendedItem.ts
  src/services/home/query/useGetSellerPick.ts
  src/services/sellerItem/mutation/usePatchItemStatus.ts
  src/services/sellerItem/mutation/usePostItem.ts
  src/services/sellerItem/mutation/usePutItem.ts
  src/types/common/ItemType.types.ts
  src/types/item.types.ts
  src/utils/checkForceUpdate.ts
  src/utils/dateUtils.ts
  src/utils/formatDate.ts
  src/utils/useCopyUrl.ts
Labels: bug

#77 [FEAT] 유저 톡박스, 유저/셀러 상품 상세 페이지 #69
  src/api/faqCard/handleFaqCard.api.ts
  src/api/likes/handleItemLikes.api.ts
  src/api/sellerMyProfile/getMarket.api.ts
  src/api/talkBox/handleQuestionCategory.api.ts
  src/api/talkBox/handleTalkBox.api.ts
  src/components/common/ChatBarTextArea.tsx
  src/components/common/item/ItemDetailProfile.tsx
  src/components/common/item/itemDetail/ItemDetailFaqCard.tsx
  src/components/common/item/itemDetail/ItemDetailInfo.tsx
  src/components/common/item/itemDetail/ItemDetailProfile.tsx
  src/components/common/item/itemDetail/customSwiper.css
  src/components/common/talkBox/ChatBubble.tsx
  src/components/common/talkBox/TalkBoxSellerProfile.tsx
  src/components/index.ts
  src/components/seller/item/faq/FaqItemBanner.tsx
  src/components/seller/talkBox/SellerReplyBubble.tsx
  src/components/seller/talkBox/SingleQuestionBottomSheet.tsx
  src/components/user/itemDetail/UserNav.tsx
  src/components/user/talkBox/CategorySelectWrapper.tsx
  src/components/user/talkBox/ChatBubble.tsx
  src/components/user/talkBox/TalkBoxItemCard.tsx
  src/constants/api.ts
  src/hooks/useInfiniteScroll.ts
  src/pages/index.ts
  src/pages/seller/item/ItemDetailDummyData.ts
  src/pages/seller/item/ItemRegistrationPage.tsx
  src/pages/seller/item/SellerItemDetailPage.tsx
  src/pages/seller/item/faq/FaqEditPage.tsx
  src/pages/seller/talkBox/BulkReplyPage.tsx
  src/pages/user/itemDetail/UserItemDetailPage.tsx
  src/pages/user/talkBox/UserChatPage.tsx
  src/routes/AppRouter.tsx
  src/routes/path.ts
  src/services/likes/query/useGetItemLikeCounts.ts
  src/services/seller/query/useGetSellerOverview.ts
  src/services/sellerFaqCard/query/useGetFaqCard.tsx
  src/services/sellerFaqCard/query/useGetFaqCardByCategory.ts
  src/services/sellerFaqCard/query/useGetItemFaqCategory.tsx
  src/services/sellerItem/query/useGetMarketItemDetail.ts
  src/services/talkBox/mutation/usePostUserQuestion.ts
  src/services/talkBox/query/useGetUserCategoryList.ts
  src/services/talkBox/query/useGetUserTalkBoxHistory.ts
  src/types/common/FAQ.types.ts
  src/types/common/FaqCardType.types.ts
  src/types/common/ItemType.types.ts
  src/types/seller/SellerProfile.types.ts
  src/types/seller/TalkBox.types.ts
Labels: bug, feature, design

#81 [FEAT] 기타 디테일 수정
  src/assets/icon/common/Calendar.svg
  src/assets/icon/common/Camera.svg
  src/assets/icon/common/CameraCircle.svg
  src/assets/icon/common/RadioButtonChecked.svg
  src/assets/icon/common/RadioButtonUnchecked.svg
  src/components/common/VanillaProfileImageUploader.tsx
  src/components/seller/common/RadioInputSelector.tsx
  src/components/seller/item/faq/FaqImageUploader.tsx
  src/components/seller/item/registration/ItemForm.tsx
  src/components/seller/item/registration/ItemImageUploader.tsx
  src/components/seller/my/SellerMyProfileEdit.tsx
  src/components/user/common/ItemGridCard.tsx
  src/components/user/home/HomeCommonSection.tsx
  src/components/user/home/TopBannerSwiper.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/auth/UserTypeSelectPage.tsx
  src/pages/seller/item/ItemRegistrationPage.tsx
  src/pages/user/home/HomePage.tsx
  src/pages/user/my/MyQuestion.tsx
  src/schemas/itemSchema.ts
  src/types/common/ItemType.types.ts
Labels: bug, feature, chore, design

#109 [FIX] 찜 오류 수정
  src/pages/user/home/CategoryPage.tsx
  src/pages/user/home/EndingSoonPage.tsx
  src/pages/user/home/HomePage.tsx
  src/pages/user/itemDetail/UserItemDetailPage.tsx
  src/pages/user/search/SearchPage.tsx
  src/services/likes/mutation/usePatchItemLike.ts
  src/services/likes/mutation/usePatchSellerLike.ts
  src/services/likes/mutation/usePostItemLike.ts
  src/services/likes/mutation/usePostSellerLike.ts
Labels: bug
