Repository INFLUY/Influy-FE, pull requests merged in 2025-07, with the labels that each got.

#34 [FEAT] 답변 생성/수정 페이지 구현
  .github/ISSUE_TEMPLATE/✨-feature-request.md
  .github/ISSUE_TEMPLATE/❓-etc-template.md
  .github/ISSUE_TEMPLATE/🐛-bug-report.md
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/assets/icon/common/Delete2Icon.svg
  src/assets/icon/common/Edit2Icon.svg
  src/assets/icon/seller/ImageResizeIcon.svg
  src/components/common/FormTextInput.tsx
  src/components/common/PageHeader.tsx
  src/components/common/SnackBar.tsx
  src/components/common/ToggleButton.tsx
  src/components/index.ts
  src/components/seller/common/Button.tsx
  src/components/seller/common/Button.types.ts
  src/components/seller/common/CategoryChip.tsx
  src/components/seller/item/administration/ExternalLinkBottomSheet.tsx
  src/components/seller/item/faq/FaqImageUploader.tsx
  src/components/seller/item/faq/FaqItemBanner.tsx
  src/components/seller/item/faq/VanillaCategoryMultiSelector.tsx
  src/components/seller/item/registration/ItemForm.tsx
  src/components/seller/my/AddNoticeBottomSheet.tsx
  src/hooks/useSingleImageUploader.ts
  src/pages/index.ts
  src/pages/seller/item/faq/FaqEditPage.tsx
  src/pages/seller/item/faq/FaqRegistrationCategoryPage.tsx
  src/pages/seller/item/faq/FaqRegistrationPage.tsx
  src/routes/AppRouter.tsx
  src/routes/path.ts
  src/schemas/faqSchema.ts
  src/utils/formatDate.ts
Labels: feature, design

#38 [FEAT] API 초기 연동 세팅, 에러 바운더리 처리, 공지사항 연동
  .gitignore
  eslint.config.js
  package-lock.json
  package.json
  src/App.tsx
  src/api/axiosInstance.ts
  src/api/notification/handleNotification.api.ts
  src/api/utils.ts
  src/components/common/LoadingSpinner.tsx
  src/components/common/NoticeBanner.tsx
  src/components/error/ErrorContent.tsx
  src/components/index.ts
  src/components/seller/item/administration/AdminItemBottomSheet.tsx
  src/components/seller/my/AddNoticeBottomSheet.tsx
  src/components/seller/my/AddNoticeButton.tsx
  src/components/seller/my/EditNoticeBottomSheet.tsx
  src/components/seller/myMarket/notice/Notice.tsx
  src/components/user/common/Item.tsx
  src/components/user/seller/SellerNoticeBottomSheet.tsx
  src/components/user/seller/SellerProfileHeader.tsx
  src/constants/api.ts
  src/hooks/auth/useStrictSellerId.ts
  src/hooks/useInfiniteScroll.ts
  src/libs/error/UIError.ts
  src/pages/error/ErrorPage.tsx
  src/pages/error/NotFound.tsx
  src/pages/index.ts
  src/pages/seller/notice/NoticePage.tsx
  src/pages/seller/sellerMyPage/SellerMyProfile.tsx
  src/pages/user/sellerProfile/SellerProfile.tsx
  src/routes/AppRouter.tsx
  src/routes/AuthInterceptor.tsx
  src/routes/path.ts
  src/services/notification/mutation/useDeleteNotification.tsx
  src/services/notification/mutation/usePatchNotification.tsx
  src/services/notification/mutation/usePostNotification.tsx
  src/services/notification/query/useGetNotification.tsx
  src/services/notification/query/useGetPrimaryNotification.tsx
  src/store/authStore.ts
  src/styles/global.css
  src/types/common/NoticeType.types.ts
Labels: feature, design

#37 [Feat] 상품 생성/수정 페이지 FAQ 탭 #33
  package-lock.json
  package.json
  src/assets/icon/common/AddIcon.svg
  src/assets/icon/common/ArrowRight.svg
  src/assets/icon/common/ArrowRightMini.svg
  src/assets/icon/common/DarkPinIcon.svg
  src/assets/icon/common/LightPinIcon.svg
  src/assets/icon/common/MinusIcon.svg
  src/assets/icon/seller/DndIcon.svg
  src/components/common/BottomSheet.tsx
  src/components/common/FormTextInput.tsx
  src/components/index.ts
  src/components/seller/common/Button.tsx
  src/components/seller/common/DetailInput.tsx
  src/components/seller/item/EmptyCategoryPlaceholder.tsx
  src/components/seller/item/registration/FaqListEdit.tsx
  src/hooks/useBottomSheetGesture.ts
  src/pages/index.ts
  src/pages/seller/item/ItemRegistrationPage.tsx
  src/pages/seller/item/ItemRegistrationTabs.tsx
  src/pages/seller/item/faq/FaqRegistrationPage.tsx
  src/routes/AppRouter.tsx
  src/routes/path.ts
  src/types/common/ItemType.types.ts
  vite.config.ts
Labels: feature

#41 [DESIGN] 셀러 마이페이지, 셀러 페이지 유저뷰 디자인 수정
  src/assets/icon/common/Add1Icon.svg
  src/assets/icon/common/Add2Icon.svg
  src/assets/icon/common/Edit1Icon.svg
  src/assets/icon/common/EyeIcon.svg
  src/assets/icon/common/HeartActive.svg
  src/assets/icon/common/HeartIcon.svg
  src/assets/icon/common/SettingsIcon.svg
  src/assets/icon/common/ShareIcon.svg
  src/assets/icon/common/sns/EmailIcon.svg
  src/assets/icon/common/sns/InstagramIcon.svg
  src/assets/icon/common/sns/TiktokIcon.svg
  src/assets/icon/common/sns/YoutubeIcon.svg
  src/assets/icon/seller/ImageResizeIcon.svg
  src/assets/icon/user/Heart.svg
  src/assets/icon/user/HeartActive.svg
  src/components/common/ExternalLinkChip.tsx
  src/components/common/LoadingSpinner.tsx
  src/components/common/NoticeBanner.tsx
  src/components/common/ScrapButton.tsx
  src/components/common/SellerProfileCard.tsx
  src/components/common/item/ItemDetailInfo.tsx
  src/components/index.ts
  src/components/seller/common/Button.tsx
  src/components/seller/my/SellerMyProfileHeader.tsx
  src/components/user/common/Chip.tsx
  src/components/user/common/Item.tsx
  src/hooks/useBottomSheetGesture.ts
  src/pages/seller/item/ItemRegistrationPage.tsx
  src/pages/seller/item/faq/FaqEditPage.tsx
  src/pages/seller/item/faq/FaqRegistrationPage.tsx
  src/pages/seller/notice/NoticePage.tsx
  src/pages/seller/sellerMyPage/MySelectionTab.tsx
  src/pages/seller/sellerMyPage/SellerMyProfile.tsx
  src/pages/user/sellerProfile/SelectionTab.tsx
  src/pages/user/sellerProfile/SellerProfile.tsx
  src/services/notification/query/useGetNotification.tsx
  src/styles/global.css
  src/utils/getTimeChipText.ts
Labels: bug, feature, design

#42 [FEAT] 홈 화면 ui 디자인 #39
  public/banner.png
  public/profile1.png
  public/profile2.png
  public/profile3.png
  public/profile4.png
  src/assets/icon/common/ArrowIcon.svg
  src/assets/icon/common/ArrowLeftIcon.svg
  src/assets/icon/common/ArrowRight.svg
  src/assets/icon/common/BellIcon.svg
  src/assets/icon/common/CalendarNavbar.svg
  src/assets/icon/common/HeartNavbar.svg
  src/assets/icon/common/InfluyIcon.svg
  src/assets/icon/common/MyNavbar.svg
  src/assets/icon/common/SearchIcon.svg
  src/assets/icon/common/TalkBoxIcon.svg
  src/components/common/BottomNavBar.tsx
  src/components/common/PageHeader.tsx
  src/components/common/ScrapButton.tsx
  src/components/common/card/HorizontalRankingCard.tsx
  src/components/common/card/ItemAlbumCard.tsx
  src/components/common/chip/PeriodChip.tsx
  src/components/common/home/HomeCommonSection.tsx
  src/components/common/home/HomeSectionTitle.tsx
  src/components/common/item/ItemDetailFaqCard.tsx
  src/components/common/item/ItemDetailInfo.tsx
  src/components/common/item/customSwiper.css
  src/components/index.ts
  src/components/seller/common/Button.tsx
  src/components/seller/common/CategoryChip.tsx
  src/components/seller/home/MyProductStatus.tsx
  src/components/seller/home/statusCardSwiper.css
  src/components/user/home/TopBannerSwiper.tsx
  src/components/user/home/topBannerSwiper.css
  src/pages/common/home/CategoryPage.tsx
  src/pages/common/home/EndingSoonPage.tsx
  src/pages/common/home/TrendingPage.tsx
  src/pages/home/Home.tsx
  src/pages/home/HomeMockData.ts
  src/pages/home/HomePage.tsx
  src/pages/index.ts
  src/pages/seller/SellerHomePage.tsx
  src/routes/AppRouter.tsx
  src/routes/path.ts
  src/types/common/ItemType.types.ts
Labels: feature

#61 [FIX] Reissue HTTP 메서드 수정
  src/api/auth/authInterceptor.ts
  src/api/auth/getReissue.api.ts
  src/store/authStore.ts
Labels: bug

#65 [CHORE] App Router 경로 추가
  src/routes/AppRouter.tsx
Labels: chore
