Repository INFLUY/Influy-FE, pull requests merged in 2025-06, with the labels that each got.

#15 [FEAT] 공지사항 편집 페이지 UI 구현
  src/assets/icon/common/DarkPinIcon.svg
  src/assets/icon/common/PlusIcon.svg
  src/components/common/PageHeader.tsx
  src/components/index.ts
  src/components/layout/GlobalLayout.tsx
  src/components/seller/common/Button.tsx
  src/components/seller/common/DetailInput.tsx
  src/components/seller/common/SellerModal.tsx
  src/components/seller/item/administration/AdminItemBottomSheet.tsx
  src/components/seller/item/administration/EditStatusChip.tsx
  src/components/seller/item/administration/SellerMyItem.tsx
  src/components/seller/my/AddNoticeBottomSheet.tsx
  src/components/seller/my/AddNoticeButton.tsx
  src/components/seller/my/EditNoticeBottomSheet.tsx
  src/components/user/common/Chip.tsx
  src/components/user/common/Item.tsx
  src/hooks/useAutoResizeTextArea.ts
  src/pages/index.ts
  src/pages/seller/notice/NoticePage.tsx
  src/pages/seller/sellerMyPage/MySelectionTab.tsx
  src/pages/seller/sellerMyPage/SellerMyProfile.tsx
  src/pages/user/sellerProfile/SelectionTab.tsx
  src/pages/user/sellerProfile/SellerProfile.tsx
  src/routes/AppRouter.tsx
  src/routes/path.ts
  src/types/common/ItemType.types.ts
  src/types/common/NoticeType.types.ts
  src/types/seller/MyItem.types.ts
  src/types/seller/SellerModalProps.types.ts
  src/types/types.ts
  src/utils/formatDate.ts
Labels: feature, design, refactor

#18 [Feat] 셀러 상품 등록 페이지 #13
  .gitignore
  package-lock.json
  package.json
  src/assets/icon/common/Calendar.svg
  src/assets/icon/common/Camera.svg
  src/assets/icon/common/CheckBox24Off.svg
  src/assets/icon/common/CheckBox24On.svg
  src/assets/icon/common/Delete.svg
  src/assets/icon/common/DropdownArrow.svg
  src/assets/icon/common/StatisticIcon.svg
  src/components/common/PageHeader.tsx
  src/components/common/Tab.tsx
  src/components/index.ts
  src/components/seller/common/Button.tsx
  src/components/seller/common/Button.types.ts
  src/components/seller/common/CategoryChip.tsx
  src/components/seller/common/DetailInput.tsx
  src/components/seller/common/RadioBottomSheet.tsx
  src/components/seller/item/administration/EditStatusChip.tsx
  src/components/seller/item/administration/ExternalLinkBottomSheet.tsx
  src/components/seller/item/registration/CategoryMultiSelector.tsx
  src/components/seller/item/registration/DateTimePicker.css
  src/components/seller/item/registration/DateTimePicker.tsx
  src/components/seller/item/registration/FormTextInput.tsx
  src/components/seller/item/registration/ItemForm.tsx
  src/components/seller/item/registration/ItemImageUploader.tsx
  src/components/seller/item/registration/ItemSection.tsx
  src/components/seller/item/registration/PeriodDropdown.tsx
  src/components/seller/my/AddNoticeBottomSheet.tsx
  src/components/user/common/Chip.tsx
  src/pages/seller/item/ItemRegistrationPage.tsx
  src/schemas/itemSchema.ts
  src/styles/global.css
  src/types/item.types.ts
  src/utils/formatDate.ts
Labels: feature, design

#20 [FEAT] 답변 생성 페이지 카테고리
  package-lock.json
  package.json
  src/assets/icon/common/PlusIcon.svg
  src/assets/icon/common/XIcon.svg
  src/assets/icon/seller/FolderIcon.svg
  src/components/common/PageHeader.tsx
  src/components/index.ts
  src/components/seller/common/Button.tsx
  src/components/seller/common/Button.types.ts
  src/components/seller/common/CategoryChip.tsx
  src/components/seller/common/TipTooltip.tsx
  src/components/seller/item/faq/VanillaCategoryMultiSelector.tsx
  src/components/seller/item/registration/CategoryMultiSelector.tsx
  src/components/seller/item/registration/FormTextInput.tsx
  src/components/seller/item/registration/ItemForm.tsx
  src/constants/productCategories.ts
  src/pages/index.ts
  src/pages/seller/item/ItemRegistrationPage.tsx
  src/pages/seller/item/faq/FaqRegistrationCategoryPage.tsx
  src/pages/seller/sellerMyPage/MySelectionTab.tsx
  src/pages/user/sellerProfile/SellerProfile.tsx
  src/routes/AppRouter.tsx
  src/routes/path.ts
  src/types/common/CategoryType.types.ts
  src/types/item.types.ts
Labels: bug, feature, design, refactor

#28 [CHORE] 탭 텍스트 색상 수정 및 stopPropagation
  src/components/common/BottomSheet.tsx
  src/components/common/Tab.tsx
  src/components/seller/item/administration/EditStatusChip.tsx
  src/components/seller/item/administration/SellerMyItem.tsx
Labels: bug, design
